# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flexjob/flexjob.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from flexjob.protos.google.longrunning import (
    operations_pb2 as google_dot_longrunning_dot_operations__pb2,
)

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x15\x66lexjob/flexjob.proto\x12\x07\x66lexjob\x1a#google/longrunning/operations.proto"4\n\x10\x43reateJobRequest\x12\x10\n\x08instance\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t2P\n\x07\x46lexJob\x12\x45\n\tCreateJob\x12\x19.flexjob.CreateJobRequest\x1a\x1d.google.longrunning.Operationb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "flexjob.flexjob_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _CREATEJOBREQUEST._serialized_start = 71
    _CREATEJOBREQUEST._serialized_end = 123
    _FLEXJOB._serialized_start = 125
    _FLEXJOB._serialized_end = 205
# @@protoc_insertion_point(module_scope)
