"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class CreateJobRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INSTANCE_FIELD_NUMBER: builtins.int
    ACTION_FIELD_NUMBER: builtins.int
    instance: builtins.str
    action: builtins.str
    def __init__(
        self,
        *,
        instance: builtins.str = ...,
        action: builtins.str = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "action", b"action", "instance", b"instance"
        ],
    ) -> None: ...

global___CreateJobRequest = CreateJobRequest
